sudo: false

language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"

env:
    -
    - LANG=

install:
    - python setup.py --quiet install
    - pip install pep8 pyflakes

script:
    - ./test_rstcheck.py
    - ./test.bash
    - python -m doctest -v README.rst rstcheck.py
    - if [ "$TRAVIS_PYTHON_VERSION" != "2.7" ]; then rstcheck examples/good.rst README.rst; fi
    - pep8 ./*.py
    - pyflakes ./*.py
