language: python

python:
    - "2.7"
    - "3.2"
    - "3.3"

install:
    - python setup.py --quiet install

script:
    - ./test_rstcheck.py
    - ./test.bash
    - rstcheck good.rst
    - rstcheck --ignore=cpp,python README.rst
